// <auto-generated />
using System;
using Audree.Ssa.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Audree.Ssa.Infrastructure.Migrations
{
    [DbContext(typeof(SSADbContext))]
    [Migration("20190919105118_MaterialMst")]
    partial class MaterialMst
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Audree.Ssa.Core.Model.Master.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode");

                    b.Property<string>("CountryName");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Audree.Ssa.Core.Model.Master.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApprovedBy");

                    b.Property<DateTime?>("ApprovedDate");

                    b.Property<int?>("ApprovedIP");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("CreatedIP");

                    b.Property<bool?>("IsActive");

                    b.Property<string>("MaterialDescription");

                    b.Property<string>("MaterialGroupName");

                    b.Property<string>("Materialcode");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int?>("ModifiedIP");

                    b.Property<int?>("Status");

                    b.HasKey("Id");

                    b.ToTable("Material","Master");
                });
#pragma warning restore 612, 618
        }
    }
}
