// <auto-generated />
using System;
using Audree.Ssa.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Audree.Ssa.Infrastructure.Migrations
{
    [DbContext(typeof(SSADbContext))]
    [Migration("20190921102514_profileMaster")]
    partial class profileMaster
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Audree.Ssa.Core.Model.Admin.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApprovedBy");

                    b.Property<DateTime?>("ApprovedDate");

                    b.Property<int?>("ApprovedIP");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("CreatedIP");

                    b.Property<string>("Description");

                    b.Property<string>("Icon");

                    b.Property<bool?>("IsActive");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int?>("ModifiedIP");

                    b.Property<int?>("Status");

                    b.HasKey("Id");

                    b.ToTable("Profile","Admin");
                });

            modelBuilder.Entity("Audree.Ssa.Core.Model.Master.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApprovedBy");

                    b.Property<DateTime?>("ApprovedDate");

                    b.Property<int?>("ApprovedIP");

                    b.Property<string>("CountryCode");

                    b.Property<string>("CountryName");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("CreatedIP");

                    b.Property<bool?>("IsActive");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int?>("ModifiedIP");

                    b.Property<int?>("Status");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Audree.Ssa.Core.Model.Master.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApprovedBy");

                    b.Property<DateTime?>("ApprovedDate");

                    b.Property<int?>("ApprovedIP");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("CreatedIP");

                    b.Property<bool?>("IsActive");

                    b.Property<string>("MaterialDescription");

                    b.Property<string>("MaterialGroupName");

                    b.Property<string>("Materialcode");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int?>("ModifiedIP");

                    b.Property<int?>("Status");

                    b.HasKey("Id");

                    b.ToTable("Material","Master");
                });

            modelBuilder.Entity("Audree.Ssa.Core.Model.Master.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action");

                    b.Property<bool>("Active");

                    b.Property<string>("Controller");

                    b.Property<bool>("DefaultMenu");

                    b.Property<string>("Icon");

                    b.Property<string>("LinkText");

                    b.Property<int?>("MenuOrder");

                    b.Property<int>("ProfileId");

                    b.HasKey("Id");

                    b.ToTable("Menu","Admin");
                });

            modelBuilder.Entity("Audree.Ssa.Core.Model.Master.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApprovedBy");

                    b.Property<DateTime?>("ApprovedDate");

                    b.Property<int?>("ApprovedIP");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("CreatedIP");

                    b.Property<bool?>("IsActive");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int?>("ModifiedIP");

                    b.Property<string>("RoleDescription");

                    b.Property<int?>("Status");

                    b.HasKey("Id");

                    b.ToTable("Role","Master");
                });

            modelBuilder.Entity("Audree.Ssa.Core.Model.Master.Salutation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApprovedBy");

                    b.Property<DateTime?>("ApprovedDate");

                    b.Property<int?>("ApprovedIP");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("CreatedIP");

                    b.Property<string>("Description");

                    b.Property<bool?>("IsActive");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int?>("ModifiedIP");

                    b.Property<int?>("Status");

                    b.HasKey("Id");

                    b.ToTable("Salutation","Master");
                });

            modelBuilder.Entity("Audree.Ssa.Core.Model.Master.UOM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApprovedBy");

                    b.Property<DateTime?>("ApprovedDate");

                    b.Property<int?>("ApprovedIP");

                    b.Property<int>("Code");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("CreatedIP");

                    b.Property<string>("FullName");

                    b.Property<bool?>("IsActive");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int?>("ModifiedIP");

                    b.Property<int>("SerialNumber");

                    b.Property<int?>("Status");

                    b.Property<int>("UOMStatus");

                    b.HasKey("Id");

                    b.ToTable("UOM","Master");
                });
#pragma warning restore 612, 618
        }
    }
}
